samostalniki_feste = {"e Tradtion -en": "tradicija",
    "r Brauch -¨e": "navada, šega, običaj",
    "s Festessen": "praznični obrok",
    "r Geburtstag -e": "rojstni dan",
    "e Geburtstagsparty -s": "rojstnodnevna zabava",
    "e Grillparty -s": "piknik",
    "s Geschenk -e": "darilo",
    "e Feier -n": "praznovanje",
    "r Feiertag -e": "praznik",
    "r Namenstag -e": "god",
    "e Taufe -n": "krst",
    "e Hochzeit -en": "poroka",
    "r Hochzeitstag -e": "obletnica poroke",
    "r Jahrestag -e": "obletnica",
    "e Einladung -en": "vabilo",
    "r Wettbewerb -e": "tekmovanje",
    "s Fest": "praznik",
    "r Sekt": "peneče vino",
    "r Champagner": "šampanjec",
    "r Nikolaustag -e": "Miklavž",
    "r Heiligabend": "sveti večer ",
    "r Stephanstag -e": "Štefanovo",
    "r Silvester": "Silvestor",
    "r Valentinstag": "valentinovo",
    "r Aschermittwoch": "pepelnična sreda",
    "e Fastenzeit -en": "postni čas",
    "r Muttertag": "materinski dan",
    "r Vatertag": "očetovski dan",
    "s Ostern": "velika noč",
#    "r Karneval/r Fasching/e Fastnacht": "pust",
    "r Rosenmontag": "pushtni ponedeljek",
    "r Kuss -¨e": "poljub",
    "s Küsschen -/": "poljubček",
    "e Menge -n": "množica",
    "s Holz": "les",
    "r Umzut -¨e": "sprevod",
    "r Karnevalsumzug -¨e": "karnevalski sprevod",
    "s Rheinland": "renska dežela",
    "s Osterei -er": "pirh",
    "s Sommerfest -e": "poletna zabava",
    "s Straßenfest -e": "ulična zabava",
    "r Schmuck -/": "okrasje, nakit",
    "r Almamtreib": "kravji bal",
    "e Alm -en": "planina",
    "s Tal -¨er": "dolina",
    "r Stall -¨e": "hlev",
    "s Feld -er": "polje",
    "s Glück": "sreča"}
